baseURL: "https://hyasuda.github.io/"
languageCode: "ja"
title: "Hiromasa Yasuda"
theme: "hugo-profile"
relativeURLs: true

# Add for Github pages
publishDir: "docs"
canonifyurls: true

googleanalytics: UA-136790295-1
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3

  favicon: "/images/hyasuda_favicon.png"
  description: "Hiromasa Yasuda's webpage."

  # Navbar Menus
  customMenus:
    - name: "Blog"
      Url: "/blog"

  # home
  disable_home: false
  profile_image: "/images/hyasuda_draw_small.jpg"
  name: "Hiromasa Yasuda"
  profession: "安田　浩昌"
  github: "https://github.com/hyasuda"
  linkedin: "https://www.linkedin.com/in/hiromasa-yasuda-51655b217/"
  # twitter: "https://twitter.com/"
  # instagram: "https://instagram.com/"
  # facebook: "https://facebook.com"

  # About
  disable_about: false
  # descripe_l1_person: "Hi, I'm Profile, a passionate researcher at a private company."
  # descripe_l2_person: "This pages show my private products."
  # descripe_l3_person: "You can find my workd [here](#projects)."
  descripe_l1_person: "民間企業で研究職をしています."
  descripe_l2_person: "このページでは、プライベートな成果物を発信していく予定です."
  descripe_l3_person: "成果物の情報は [こちら](#projects) から探すことができます."
  skills:
    - name: C++
      percentage: 50
    - name: Hugo
      percentage: 15
    - name: Rust
      percentage: 15
    - name: Electrics 
      percentage: 50
    - name: Accelerator
      percentage: 60

  # Experience
  disable_experience: false
  experience:
    - company: "Private Company"
      role: "Software developer"
      startdate: Feb 2021
      enddate: present
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Facebook"
      role: "Fullstack developer"
      startdate: Mar 2020
      enddate: Dec 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Amazon"
      role: "Fullstack developer"
      startdate: Feb 2019
      enddate: Jan 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
  # disable_experience: false
  # experience:
  #   - company: "Private Company (Manufacturing)"
  #     role: "Researcher"
  #     startdate: Apr 2021
  #   - company: "University of Tokyo"
  #     role: "Research Fellowship for Young Scientists"
  #     startdata: Apr 2018
  #     enddata: Mar 2021
      

  # Education
  disable_education: false
  education:
    - degree: "Withdraw from the doctorial course"
      branch: "Science"
      university: "University of Tokyo"
      startedyear: "2018"
      graduation: "2021"
    - degree: "Master"
      branch: "Science"
      university: "University of Tokyo"
      startedyear: "2016"
      graduation: "2018"
    - degree: "Bachelor"
      branch: "Science"
      university: "Saitama University"
      startedyear: "2012"
      graduation: "2016"

  # Projects
  disable_projects: true
  projects:
    - name: "Example project without details"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"

  # Achievements
  disable_achievements: true
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition win ner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "hyasuda.work@gmail.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: true
  tweet: false
